VERSION = '1.6'

# Fixed constants used by PyAMPR set here
DEFAULT_CLEVS = [75, 325]
DEFAULT_GRID_DEL = 2.0
DEFAULT_VAR = '10A'
DEFAULT_CHAN_LIST = ['10', '19', '37', '85']
DEFAULT_SWATH_SIZE = 50
DEFAULT_NAV_SIZE = 18
DEFAULT_BAD_DATA = -999.0
DEFAULT_SWATH_LEFT = -44.1
DEFAULT_PROJECT_NAME = 'OLYMPEX'
